---
abstract: 'check your source for encoding misbehavior.'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mojibake
requires:
  File::Spec: 0
  Test::Builder: 0
version: 0.2
