---
abstract: 'check your source for encoding misbehavior.'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Encode: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Builder::Tester: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mojibake
recommends:
  Unicode::CheckUTF8: 0
requires:
  File::Spec::Functions: 0
  Pod::Usage: 0
  Test::Builder: 0
  bytes: 0
  integer: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Test-Mojibake/issues
  homepage: https://github.com/creaktive/Test-Mojibake
  repository: git://github.com/creaktive/Test-Mojibake.git
version: 0.9
